### ISSUE TITLE
Fails to parse lone opening brace

### ISSUE THREAD

**Issue by mvz** [ammar/regexp_parser#59]
Attempting to parse `/{/` results in an error:
```ruby
Regexp::Parser.parse '{'
# Regexp::Scanner::PrematureEndError (Premature end of pattern at {)
```

However, for MRI this is perfectly fine (although it's equivalent to `/\{/`).
```ruby
/{/
#=> /{/
```

**Comment by janosch-x** [comment]
Hi @mvz and thanks for reporting.

May I ask, did you encounter this in a "real-life" scenario or were you testing for edge cases?

So far, the policy for this gem has been not to support these "quirky" metachar/literal edge cases, as described in #15, particularly in [this comment]( https://github.com/ammar/regexp_parser/issues/15#issuecomment-212884778 ) and the following ones.

If these quirks turn out to be commonly depended upon, we might have to reconsider, though.

MRI behavior is quite inconsistent here looking at other metachar pairs, but at least it hasn't changed since Ruby 1.9.3.

```ruby
/{/ # => /{/
/}/ # => /}/
/[/ # => SyntaxError (premature end of char-class: /[/)
/]/ # => /]/
/(/ # => SyntaxError (end pattern with unmatched parenthesis: /(/)
/)/ # => SyntaxError (unmatched close parenthesis: /)/)
```

**Comment by janosch-x** [comment]
the error is now being caught by `mutant`, so i'll close this issue.
